### ISSUE TITLE
Error on start up this morning

### ISSUE THREAD

**Issue by Shindo-Aardwolf** [tallimos/AardPlugins#1]
`Attempting to reload plugin #3 (EpicCalendar)
[EpicCAL] Thank you for installing Tallimos' Epic Calendar v2.12. Please see ecal help for more information.

Run-time error
Plugin: Tallimos_EpicCalendar (called from world: Aardwolf)
Function/Sub: EpicBoard called by trigger
Reason: processing trigger "" when matching line: "|  6346|01 Mar 20:19| Shaelynne   | OC OC + WINDS at 8:30PM             |   3|"
[string "Plugin: Tallimos_EpicCalendar"]:1266: attempt to index field 'Time Table' (a nil value)
stack traceback:
        [string "Plugin: Tallimos_EpicCalendar"]:1266: in function 'PopulateTimeTable'
        [string "Plugin: Tallimos_EpicCalendar"]:1107: in function 'AddEpic'
        [string "Plugin: Tallimos_EpicCalendar"]:879: in function <[string "Plugin: Tallimos_EpicCalendar"]:872>
Trigger function "EpicBoard" not found or had a previous error.
Trigger function "EpicBoard" not found or had a previous error.`

The calendar then displays "correctly" with `ecal list`

**Comment by tallimos** [comment]
Try updating to newest version and let me know if it still happens

**Comment by Shindo-Aardwolf** [comment]
From what I can tell the new version has fixed it.
Thanks
I'll close the issue now
